# Generated by Django 6.0.2 on 2026-03-30 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('email', models.EmailField(
                    max_length=254,
                    unique=True,
                    verbose_name='Email'
                )),
                ('full_name', models.CharField(
                    max_length=200,
                    verbose_name='ФИО'
                )),
                ('comment', models.TextField(
                    blank=True,
                    null=True,
                    verbose_name='Комментарий'
                )),
                ('created_at', models.DateTimeField(
                    auto_now_add=True,
                    verbose_name='Дата создания'
                )),
                ('updated_at', models.DateTimeField(
                    auto_now=True,
                    verbose_name='Дата обновления'
                )),
                ('owner', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='clients',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Владелец'
                )),
            ],
            options={
                'verbose_name': 'Получатель рассылки',
                'verbose_name_plural': 'Получатели рассылки',
                'ordering': ['-created_at'],
                'permissions': [
                    ('can_view_all_clients', 'Может просматривать всех получателей'),
                ],
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('start_time', models.DateTimeField(
                    verbose_name='Дата и время начала'
                )),
                ('end_time', models.DateTimeField(
                    verbose_name='Дата и время окончания'
                )),
                ('status', models.CharField(
                    choices=[
                        ('created', 'Создана'),
                        ('started', 'Запущена'),
                        ('completed', 'Завершена'),
                        ('disabled', 'Отключена'),
                    ],
                    default='created',
                    max_length=20,
                    verbose_name='Статус'
                )),
                ('created_at', models.DateTimeField(
                    auto_now_add=True,
                    verbose_name='Дата создания'
                )),
                ('updated_at', models.DateTimeField(
                    auto_now=True,
                    verbose_name='Дата обновления'
                )),
                ('owner', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='mailings',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Владелец'
                )),
                ('recipients', models.ManyToManyField(
                    related_name='mailings',
                    to='mailing.client',
                    verbose_name='Получатели'
                )),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-created_at'],
                'permissions': [
                    ('can_view_all_mailings', 'Может просматривать все рассылки'),
                    ('can_disable_mailing', 'Может отключать рассылки'),
                ],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('attempt_time', models.DateTimeField(
                    auto_now_add=True,
                    verbose_name='Дата и время попытки'
                )),
                ('status', models.CharField(
                    choices=[
                        ('success', 'Успешно'),
                        ('failed', 'Не успешно'),
                    ],
                    max_length=20,
                    verbose_name='Статус'
                )),
                ('server_response', models.TextField(
                    blank=True,
                    null=True,
                    verbose_name='Ответ сервера'
                )),
                ('client', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='attempts',
                    to='mailing.client',
                    verbose_name='Получатель'
                )),
                ('mailing', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='attempts',
                    to='mailing.mailing',
                    verbose_name='Рассылка'
                )),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
                'ordering': ['-attempt_time'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('subject', models.CharField(
                    max_length=255,
                    verbose_name='Тема письма'
                )),
                ('body', models.TextField(
                    verbose_name='Тело письма'
                )),
                ('created_at', models.DateTimeField(
                    auto_now_add=True,
                    verbose_name='Дата создания'
                )),
                ('updated_at', models.DateTimeField(
                    auto_now=True,
                    verbose_name='Дата обновления'
                )),
                ('owner', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='messages',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Владелец'
                )),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
                'permissions': [
                    ('can_view_all_messages', 'Может просматривать все сообщения'),
                ],
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='mailings',
                to='mailing.message',
                verbose_name='Сообщение'
            ),
        ),
    ]
